Global-Conflicts-ArmA/gc-reforger-missions

Missions/arc/ErquyEvasion.conf, Missions/arc/ErquyEvasion.conf.meta, worlds/arc/ErquyEvasion/ErquyEvasion.ent, worlds/arc/ErquyEvasion/ErquyEvasion.ent.meta, worlds/arc/ErquyEvasion/ErquyEvasion_Layers/Briefing.layer, worlds/arc/ErquyEvasion/ErquyEvasion_Layers/Objects.layer, worlds/arc/ErquyEvasion/ErquyEvasion_Layers/Players.layer, worlds/arc/ErquyEvasion/ErquyEvasion_Layers/Vehicles.layer, worlds/arc/ErquyEvasion/ErquyEvasion_Layers/default.layer
=> TVT54 Erquy Evasion by arc

Missions/arc/ReturnOfTheWac.conf, Missions/arc/ReturnOfTheWac.conf.meta, worlds/arc/ReturnOfTheWac/ReturnOfTheWac.ent, worlds/arc/ReturnOfTheWac/ReturnOfTheWac.ent.meta, worlds/arc/ReturnOfTheWac/ReturnOfTheWac_Layers/AI.layer, worlds/arc/ReturnOfTheWac/ReturnOfTheWac_Layers/Briefing.layer, worlds/arc/ReturnOfTheWac/ReturnOfTheWac_Layers/Players.layer, worlds/arc/ReturnOfTheWac/ReturnOfTheWac_Layers/Waypoints.layer, worlds/arc/ReturnOfTheWac/ReturnOfTheWac_Layers/default.layer
=> CO29 Return of the WAC by arc

Missions/arc/WateryGrave.conf, Missions/arc/WateryGrave.conf.meta, worlds/arc/WateryGrave/WateryGrave.ent, worlds/arc/WateryGrave/WateryGrave.ent.meta, worlds/arc/WateryGrave/WateryGrave_Layers/Briefing.layer, worlds/arc/WateryGrave/WateryGrave_Layers/Players.layer, worlds/arc/WateryGrave/WateryGrave_Layers/Vehicles.layer, worlds/arc/WateryGrave/WateryGrave_Layers/default.layer
=> TVT (30-45) Watery Grave by arc

Missions/arc/RocketScience.conf, Missions/arc/RocketScience.conf.meta, worlds/arc/RocketScience/Prefabs/Hostage.et, worlds/arc/RocketScience/Prefabs/Hostage.et.meta, worlds/arc/RocketScience/RocketScience.ent, worlds/arc/RocketScience/RocketScience.ent.meta, worlds/arc/RocketScience/RocketScience_Layers/AI.layer, worlds/arc/RocketScience/RocketScience_Layers/Briefing.layer, worlds/arc/RocketScience/RocketScience_Layers/Players.layer, worlds/arc/RocketScience/RocketScience_Layers/Waypoints.layer, worlds/arc/RocketScience/RocketScience_Layers/default.layer
=> TVT (16-40) Rocket Science by arc

Missions/arc/SOBRUp.conf, Missions/arc/SOBRUp.conf.meta, worlds/arc/SOBRUp/SOBRUp.ent, worlds/arc/SOBRUp/SOBRUp.ent.meta, worlds/arc/SOBRUp/SOBRUp_Layers/AI.layer, worlds/arc/SOBRUp/SOBRUp_Layers/Briefing.layer, worlds/arc/SOBRUp/SOBRUp_Layers/BriefingSEP.layer, worlds/arc/SOBRUp/SOBRUp_Layers/BriefingSOBR.layer, worlds/arc/SOBRUp/SOBRUp_Layers/Objects.layer, worlds/arc/SOBRUp/SOBRUp_Layers/Players.layer, worlds/arc/SOBRUp/SOBRUp_Layers/Vehicles.layer, worlds/arc/SOBRUp/SOBRUp_Layers/Waypoints.layer, worlds/arc/SOBRUp/SOBRUp_Layers/default.layer
Depends on https://github.com/Global-Conflicts-ArmA/gc-reforger-units/pull/4
=> COTVT (20-35) SOBR Up by arc

Missions/arc/BarnBusters.conf, Missions/arc/BarnBusters.conf.meta, worlds/arc/BarnBusters/BarnBusters.ent, worlds/arc/BarnBusters/BarnBusters.ent.meta, worlds/arc/BarnBusters/BarnBusters_Layers/SEPplayers.layer, worlds/arc/BarnBusters/BarnBusters_Layers/USplayers.layer, worlds/arc/BarnBusters/BarnBusters_Layers/briefing.layer, worlds/arc/BarnBusters/BarnBusters_Layers/cacheSpawns.layer, worlds/arc/BarnBusters/BarnBusters_Layers/default.layer, worlds/arc/BarnBusters/BarnBusters_Layers/vehicles.layer, worlds/arc/BarnBusters/Prefabs/BarnBusters_Cache.et, worlds/arc/BarnBusters/Prefabs/BarnBusters_Cache.et.meta
requires https://github.com/Til-Weimann/tilw-mission-framework/pull/7
=> TVT (30-60) Barn Busters

Missions/arc/ShootAndScoot.conf, Missions/arc/ShootAndScoot.conf.meta, worlds/arc/ShootAndScoot/ShootAndScoot.ent, worlds/arc/ShootAndScoot/ShootAndScoot.ent.meta, worlds/arc/ShootAndScoot/ShootAndScoot_Layers/ai.layer, worlds/arc/ShootAndScoot/ShootAndScoot_Layers/briefing.layer, worlds/arc/ShootAndScoot/ShootAndScoot_Layers/default.layer, worlds/arc/ShootAndScoot/ShootAndScoot_Layers/friendlyAi.layer, worlds/arc/ShootAndScoot/ShootAndScoot_Layers/players.layer, worlds/arc/ShootAndScoot/ShootAndScoot_Layers/props.layer, worlds/arc/ShootAndScoot/ShootAndScoot_Layers/waypoints.layer
requires GC units publish with https://github.com/Global-Conflicts-ArmA/gc-reforger-units/commit/d66d2084c01496817dd9028103c4f298034153f4
=> COOP (8-15) Shoot and Scoot by arc

worlds/arc/ErquyEvasion/ErquyEvasion_Layers/Briefing.layer, worlds/arc/ErquyEvasion/ErquyEvasion_Layers/default.layer, worlds/arc/ErquyEvasion/Prefabs/ErquyEvasion_ExtractionTriggerEast.et, worlds/arc/ErquyEvasion/Prefabs/ErquyEvasion_ExtractionTriggerEast.et.meta, worlds/arc/ErquyEvasion/Prefabs/ErquyEvasion_ExtractionTriggerNorth.et, worlds/arc/ErquyEvasion/Prefabs/ErquyEvasion_ExtractionTriggerNorth.et.meta, worlds/arc/ErquyEvasion/Prefabs/ErquyEvasion_ExtractionTriggerSouth.et, worlds/arc/ErquyEvasion/Prefabs/ErquyEvasion_ExtractionTriggerSouth.et.meta
requires https://github.com/Til-Weimann/tilw-mission-framework/pull/10
=> update erquy evasion with extraction for soviets

Missions/arc/RavineRuckus.conf, Missions/arc/RavineRuckus.conf.meta, worlds/arc/RavineRuckus/RavineRuckus.ent, worlds/arc/RavineRuckus/RavineRuckus.ent.meta, worlds/arc/RavineRuckus/RavineRuckus_Layers/briefing.layer, worlds/arc/RavineRuckus/RavineRuckus_Layers/briefingCDF.layer, worlds/arc/RavineRuckus/RavineRuckus_Layers/briefingRU.layer, worlds/arc/RavineRuckus/RavineRuckus_Layers/cap.layer, worlds/arc/RavineRuckus/RavineRuckus_Layers/default.layer, worlds/arc/RavineRuckus/RavineRuckus_Layers/playersCDF.layer, worlds/arc/RavineRuckus/RavineRuckus_Layers/playersRU.layer, worlds/arc/RavineRuckus/RavineRuckus_Layers/props.layer
requires GC units publish with rebuilt CDF
=> TVT (22-44) Ravine Ruckus

Missions/FSM/CO55EntreDeux_Attack.conf, Missions/FSM/TVT62ForestTrouble.conf, Missions/FSM/TVT66BlockBusters.conf, Missions/FSM/TVT66ZherebetsRiverCache.conf, worlds/FSM/Worlds/TVT66BlockBusters/TVT66BlockBusters_Layers/Framework.layer, worlds/FSM/Worlds/TVT66ZherebetsRiverCache/TVT66ZherebetsRiverCache_Layers/Framework.layer
=> Fixed FSMs missions (Canadian update broke them)

Missions/James/IDidntStealThisConcept.conf, worlds/James/IDidntStealThisConcept/Characters/BLU/Character_UK_1989_Regulars_AMG_P.et, worlds/James/IDidntStealThisConcept/Characters/BLU/Character_UK_1989_Regulars_AMG_P.et.meta, worlds/James/IDidntStealThisConcept/Characters/BLU/Character_UK_1989_Regulars_GPMG_No1_P.et, worlds/James/IDidntStealThisConcept/Characters/BLU/Character_UK_1989_Regulars_GPMG_No1_P.et.meta, worlds/James/IDidntStealThisConcept/Characters/RED/Character_USSR_AMG_VDV_P.et, worlds/James/IDidntStealThisConcept/Characters/RED/Character_USSR_AMG_VDV_P.et.meta, worlds/James/IDidntStealThisConcept/Characters/RED/Character_USSR_MG_VDV_P.et, worlds/James/IDidntStealThisConcept/Characters/RED/Character_USSR_MG_VDV_P.et.meta, worlds/James/IDidntStealThisConcept/IDidntStealThisConcept_Layers/BLU_Players.layer, worlds/James/IDidntStealThisConcept/IDidntStealThisConcept_Layers/Briefing.layer, worlds/James/IDidntStealThisConcept/IDidntStealThisConcept_Layers/Misc.layer, worlds/James/IDidntStealThisConcept/IDidntStealThisConcept_Layers/RED_Players.layer
Changed player count and adjusted ratio, now 2:3 max 60 players. Removed Recce section from UK, added MG team to USSR. Increase MG ammo for MG section on UK side.
Changed OBJ marker to better show the capture area. Callsigns fixed.
Brief adjusted to reflect changes.
Config adjusted to reflect changes.
=> TVT(45-60) I Didn't Steal this Concept - Update

Missions/James/LacourtManor.conf, Missions/James/LacourtManor.conf.meta, worlds/James/LacourtManor/Characters/BLU/Character_UK_1983_Regulars_AMG_P.et, worlds/James/LacourtManor/Characters/BLU/Character_UK_1983_Regulars_AMG_P.et.meta, worlds/James/LacourtManor/Characters/BLU/Character_UK_1983_Regulars_GPMG_No1_P.et, worlds/James/LacourtManor/Characters/BLU/Character_UK_1983_Regulars_GPMG_No1_P.et.meta, worlds/James/LacourtManor/Characters/BLU/Character_UK_1983_Regulars_Sergeant_P.et, worlds/James/LacourtManor/Characters/BLU/Character_UK_1983_Regulars_Sergeant_P.et.meta, worlds/James/LacourtManor/LacourtManor.ent, worlds/James/LacourtManor/LacourtManor.ent.meta, worlds/James/LacourtManor/LacourtManor_Layers/blu_brief.layer, worlds/James/LacourtManor/LacourtManor_Layers/blu_players.layer, worlds/James/LacourtManor/LacourtManor_Layers/map_objects.layer, worlds/James/LacourtManor/LacourtManor_Layers/misc.layer, worlds/James/LacourtManor/LacourtManor_Layers/red_brief.layer, worlds/James/LacourtManor/LacourtManor_Layers/red_players.layer
New mission
Soviet motor rifle attack on understrength Brit platoon
=> TVT(40-54) Lacourt Manor

Missions/Woody/TVTXX_Waterside_Punchup.conf, Missions/Woody/TVTXX_Waterside_Punchup.conf.meta, worlds/Woody/TVTXX_Waterside_Punchup/TVTXX_Waterside_Punchup.ent, worlds/Woody/TVTXX_Waterside_Punchup/TVTXX_Waterside_Punchup.ent.meta, worlds/Woody/TVTXX_Waterside_Punchup/TVTXX_Waterside_Punchup_Layers/briefing.layer, worlds/Woody/TVTXX_Waterside_Punchup/TVTXX_Waterside_Punchup_Layers/briefing_opfor.layer, worlds/Woody/TVTXX_Waterside_Punchup/TVTXX_Waterside_Punchup_Layers/briefing_uk.layer, worlds/Woody/TVTXX_Waterside_Punchup/TVTXX_Waterside_Punchup_Layers/default.layer, worlds/Woody/TVTXX_Waterside_Punchup/TVTXX_Waterside_Punchup_Layers/framework.layer, worlds/Woody/TVTXX_Waterside_Punchup/TVTXX_Waterside_Punchup_Layers/mapmarkers.layer, worlds/Woody/TVTXX_Waterside_Punchup/TVTXX_Waterside_Punchup_Layers/playergroups.layer, worlds/Woody/TVTXX_Waterside_Punchup/TVTXX_Waterside_Punchup_Layers/setdressing.layer
=> TVT (40-51) Waterside Punchup

worlds/James/LacourtManor/LacourtManor_Layers/blu_players.layer, worlds/James/LacourtManor/LacourtManor_Layers/misc.layer, worlds/James/LacourtManor/LacourtManor_Layers/red_brief.layer, worlds/James/LacourtManor/LacourtManor_Layers/red_players.layer
Adjusted AOs, reduced AT for blufor, adjusted brief a little
=> TVT Lacourt Manor update

worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_AT3_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_ATA2_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_ATA_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_AT_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_MG2_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_MG3_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_MGA2_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_MGA3_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_MGA_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_MG_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_PLT2IC_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_PL_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_RM2_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_RM_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_RTO_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_SL1_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_SL_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_TL2_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_TL_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_Testing.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_medic2_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_medic_P.et, worlds/FSM/Worlds/TVT66BlockBusters/TVT66BlockBusters_Layers/Framework.layer, worlds/FSM/Worlds/TVTBarrackHoldout/TVT67BarrackHoldout_Layers/Framework.layer, worlds/FSM/Worlds/TVTBarrackHoldout/TVT67BarrackHoldout_Layers/Players.layer
Fixed Slot names for FSM Separatists and gear getting messed up.
=> Fixed Slot names for FSM Separatists

.github/labeler.yml, .github/workflows/labeler.yml
This is a GitHub action to automatically label PRs based on the files being changed, this can be expanded upon easily.,
This will allow us to easily identify what category the PR comes under.
=> GitHub action to automatically label PRs.

Missions/Woody/COXX_Hof_Lomelsberg_Flank.conf, Missions/Woody/COXX_Hof_Lomelsberg_Flank.conf.meta, worlds/Woody/COXX_Hof_Lomelsberg_Flank/COXX_Hof_Lomelsberg_Flank.ent, worlds/Woody/COXX_Hof_Lomelsberg_Flank/COXX_Hof_Lomelsberg_Flank.ent.meta, worlds/Woody/COXX_Hof_Lomelsberg_Flank/COXX_Hof_Lomelsberg_Flank_Layers/aigroups.layer, worlds/Woody/COXX_Hof_Lomelsberg_Flank/COXX_Hof_Lomelsberg_Flank_Layers/briefing.layer, worlds/Woody/COXX_Hof_Lomelsberg_Flank/COXX_Hof_Lomelsberg_Flank_Layers/default.layer, worlds/Woody/COXX_Hof_Lomelsberg_Flank/COXX_Hof_Lomelsberg_Flank_Layers/framework.layer, worlds/Woody/COXX_Hof_Lomelsberg_Flank/COXX_Hof_Lomelsberg_Flank_Layers/mapmarkers.layer, worlds/Woody/COXX_Hof_Lomelsberg_Flank/COXX_Hof_Lomelsberg_Flank_Layers/playergroups.layer
=> Hof Lomelsberg Flank

Missions/HitTheMan/COOP62_MechanizedLeaf.conf, Missions/HitTheMan/TVT50_DamnTheDam.conf, worlds/HitTheMan/Mechanized Leaf/MechanizedLeaf_Layers/Core.layer, worlds/HitTheMan/Mechanized Leaf/MechanizedLeaf_Layers/OPFOR_QRF.layer, worlds/HitTheMan/Mechanized Leaf/MechanizedLeaf_Layers/OPFOR_Recon_WP.layer
- Changing the priority of the waypoints from 2000 -> 25, 30 for defend.
- Changing comsig & fixed lobby coms for COY HQ
- Increased/spread out the QRF attack
- Added Versions to the missions
=> Changes to my Missions

Missions/HitTheMan/COTVT62_Leaf&Saw.conf, Missions/HitTheMan/COTVT62_Leaf&Saw.conf.meta, Missions/HitTheMan/TVT50_DamnTheDam.conf, worlds/HitTheMan/DamnTheDam/Damn the Dam_Layers/Core.layer, worlds/HitTheMan/Leaf & The Saw/Leaf & Saw.ent, worlds/HitTheMan/Leaf & The Saw/Leaf & Saw.ent.meta, worlds/HitTheMan/Leaf & The Saw/Leaf & Saw_Layers/BLI_Briefings.layer, worlds/HitTheMan/Leaf & The Saw/Leaf & Saw_Layers/BLU_Players.layer, worlds/HitTheMan/Leaf & The Saw/Leaf & Saw_Layers/Core.layer, worlds/HitTheMan/Leaf & The Saw/Leaf & Saw_Layers/Markers.layer, worlds/HitTheMan/Leaf & The Saw/Leaf & Saw_Layers/OPFOR_QRF.layer, worlds/HitTheMan/Leaf & The Saw/Leaf & Saw_Layers/OPFOR_Recon_AI.layer, worlds/HitTheMan/Leaf & The Saw/Leaf & Saw_Layers/OPFOR_Town_AI.layer, worlds/HitTheMan/Leaf & The Saw/Leaf & Saw_Layers/OPF_Players.layer, worlds/HitTheMan/Leaf & The Saw/Leaf & Saw_Layers/OP_Briefings.layer, worlds/HitTheMan/Mechanized Leaf/MechanizedLeaf_Layers/Core.layer
CAF platoon with a mechanized squad attachment and mortar attachment sweep through the forest before attacking a USSR held Sawmil trainyard.
- Fixed covermap for my other 2 missions as well
=> COTVT (45-55) Leaf & Saw + Mission fixes

Missions/HitTheMan/COOP62_MechanizedLeaf.conf, worlds/HitTheMan/Mechanized Leaf/MechanizedLeaf_Layers/BLU_Players.layer, worlds/HitTheMan/Mechanized Leaf/MechanizedLeaf_Layers/Core.layer, worlds/HitTheMan/Mechanized Leaf/MechanizedLeaf_Layers/OPFOR_QRF.layer, worlds/HitTheMan/Mechanized Leaf/MechanizedLeaf_Layers/OPFOR_Recon_AI.layer, worlds/HitTheMan/Mechanized Leaf/MechanizedLeaf_Layers/OPFOR_Recon_WP.layer
- Adjusted BLU Player Units
- Adjusted Recon Platoon Waypoints Defend -> Loiter
- Added another Recon Squad
- Adjusted Counter Attack, closer than before, less time spent in forests.
- Added another 2 spawners, BRDM & Inf
=> Fixes for the 3rd Mission / Mechanized Leaf

Missions/Woody/COXX_Hof_Lomelsberg_Flank.conf
=> Updated mission name in config file

Missions/Woody/COTVTXX_Kassel_Crashers.conf, Missions/Woody/COTVTXX_Kassel_Crashers.conf.meta, worlds/Woody/COTVTXX_Kassel_Crashers/COTVTXX_Kassel_Crashers.ent, worlds/Woody/COTVTXX_Kassel_Crashers/COTVTXX_Kassel_Crashers.ent.meta, worlds/Woody/COTVTXX_Kassel_Crashers/COTVTXX_Kassel_Crashers_Layers/aigroups.layer, worlds/Woody/COTVTXX_Kassel_Crashers/COTVTXX_Kassel_Crashers_Layers/briefing.layer, worlds/Woody/COTVTXX_Kassel_Crashers/COTVTXX_Kassel_Crashers_Layers/default.layer, worlds/Woody/COTVTXX_Kassel_Crashers/COTVTXX_Kassel_Crashers_Layers/framework.layer, worlds/Woody/COTVTXX_Kassel_Crashers/COTVTXX_Kassel_Crashers_Layers/mapmarkers_NATO.layer, worlds/Woody/COTVTXX_Kassel_Crashers/COTVTXX_Kassel_Crashers_Layers/mapmarkers_PACT.layer, worlds/Woody/COTVTXX_Kassel_Crashers/COTVTXX_Kassel_Crashers_Layers/playergroups.layer, worlds/Woody/COTVTXX_Kassel_Crashers/COTVTXX_Kassel_Crashers_Layers/setdressing.layer
More COOPS RAAAAAAAAAAAAAAAAAAAAAAA
Soviet company level COTVT
I am a reviewer lmao
=> COTVT65_Kassel_Crashers

Missions/arc/StrykingOut.conf, Missions/arc/StrykingOut.conf.meta, worlds/arc/StrykingOut/StrykingOut.ent, worlds/arc/StrykingOut/StrykingOut.ent.meta, worlds/arc/StrykingOut/StrykingOut_Layers/ai.layer, worlds/arc/StrykingOut/StrykingOut_Layers/briefing.layer, worlds/arc/StrykingOut/StrykingOut_Layers/default.layer, worlds/arc/StrykingOut/StrykingOut_Layers/friendlyAI.layer, worlds/arc/StrykingOut/StrykingOut_Layers/players.layer, worlds/arc/StrykingOut/StrykingOut_Layers/props.layer, worlds/arc/StrykingOut/StrykingOut_Layers/vehicles.layer, worlds/arc/StrykingOut/StrykingOut_Layers/waypoints.layer
Rangers in strykers do an attack on a FOB and a village. Been a bit since I finished off a mission so could use a review on this one.
QRF spawns when the first of either objectives are captured.
Latest pushes to GC units will need publishing for this as they contain the ranger vic gunner/driver prefabs.
Currently requires SpaceStrider's Stryker: https://reforger.armaplatform.com/workshop/5B02128D896F7DE8-STRYKER
If we decide we don't want to add the Stryker this can be trivially converted to a JLTV + Apache mission instead.
=> COOP (30-40) Stryking Out

Missions/FSM/TVT72UnowaldCache.conf, Missions/FSM/TVT72UnowaldCache.conf.meta, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_ATA_P.et, worlds/FSM/Prefabs/Characters/Factions/OPFOR/GC_SEPARATIST/P/FSM_Rebel_SL1_P.et, worlds/FSM/Worlds/TVTUnowaldCache/TVT72UnowaldCache.ent, worlds/FSM/Worlds/TVTUnowaldCache/TVT72UnowaldCache.ent.meta, worlds/FSM/Worlds/TVTUnowaldCache/TVT72UnowaldCache_Layers/Briefing.layer, worlds/FSM/Worlds/TVTUnowaldCache/TVT72UnowaldCache_Layers/Cache.layer, worlds/FSM/Worlds/TVTUnowaldCache/TVT72UnowaldCache_Layers/Framework.layer, worlds/FSM/Worlds/TVTUnowaldCache/TVT72UnowaldCache_Layers/Markers.layer, worlds/FSM/Worlds/TVTUnowaldCache/TVT72UnowaldCache_Layers/Players.layer, worlds/FSM/Worlds/TVTUnowaldCache/TVT72UnowaldCache_Layers/Vehicles.layer
CDF search for a separatist cache.  Player count 45-72 with ratio ~2:1.
=> New mission TVT72 Unowald cache

worlds/Woody/COXX_Funf_Wege_Lodgement/COXX_Funf_Wege_Lodgement_Layers/aistatic.layer
=> Fixed static AI (and hopefully the server crashing)

worlds/IronFunnelEvent/MSN3/SovietLevies_Layers/BLUFOR/Assets.layer, worlds/IronFunnelEvent/MSN3/SovietLevies_Layers/BLUFOR/BriefingBLUFOR.layer, worlds/IronFunnelEvent/MSN3/SovietLevies_Layers/BLUFOR/Players.layer, worlds/IronFunnelEvent/MSN3/SovietLevies_Layers/MissionCore/Core.layer, worlds/IronFunnelEvent/MSN3/SovietLevies_Layers/MissionCore/EMPTYFACBRIEF.layer, worlds/IronFunnelEvent/MSN3/SovietLevies_Layers/OPFOR/AssetsOPFOR.layer, worlds/IronFunnelEvent/MSN3/SovietLevies_Layers/OPFOR/BriefingOPFOR.layer, worlds/IronFunnelEvent/MSN3/SovietLevies_Layers/OPFOR/PlayerOPFOR.layer, worlds/IronFunnelEvent/MSN3/SovietLevies_Layers/OPFOR/StaticOPFOR.layer
Put a brief summary of the mission added or updated here.
Put any specifics the mission reviewer needs to look out for or double check here.
If this mission is dependent on a pull request to GC units or core, or the TilW framework, link it here.
If this mission is dependent on a mod not currently on the GC mod list, put it here, though understand rejected or incompatible mods may require substantial changes to your mission.
=> MSN3 Fixes OIF

Missions/HitTheMan/ScreeningTheOrb.conf, worlds/HitTheMan/Screening The Orb/ScreeningTheOrb_Layers/BLUFOR/BLU_AI_Forward.layer, worlds/HitTheMan/Screening The Orb/ScreeningTheOrb_Layers/BLUFOR/BLU_AI_TOWN.layer, worlds/HitTheMan/Screening The Orb/ScreeningTheOrb_Layers/BLUFOR/BLU_Counter.layer, worlds/HitTheMan/Screening The Orb/ScreeningTheOrb_Layers/CORE/Markers.layer, worlds/HitTheMan/Screening The Orb/ScreeningTheOrb_Layers/default.layer
- Added more AI Local outside of buildings, town counter attack, marker gore and various things
=> COOP (60-79) Screening The Orb V1.5

worlds/Corax/TF141/COOPXX_Loose Ends_V1/COOPXX_LooseEnds_V1_Layers/AI.layer, worlds/Corax/TF141/COOPXX_Loose Ends_V1/COOPXX_LooseEnds_V1_Layers/Briefing.layer, worlds/Corax/TF141/COOPXX_Loose Ends_V1/COOPXX_LooseEnds_V1_Layers/Players.layer, worlds/Corax/TF141/COOPXX_Loose Ends_V1/COOPXX_LooseEnds_V1_Layers/default.layer
loose ends no longer sends the entire 3rd shock army at the rangers at game start thanks to 3 separatists that start on the bridge now also added some LOA map graphics
=> Loose ends fixes

Missions/Blue/SimonsAbatis.conf, worlds/Blue/SimonsAbatis/SimonsAbatis_Layers/BLUFOR/Briefing_BLUFOR/Briefing.layer, worlds/Blue/SimonsAbatis/SimonsAbatis_Layers/OPFOR/Briefing_OPFOR/Briefing.layer, worlds/Blue/SimonsAbatis/SimonsAbatis_Layers/OPFOR/OPFORAssets.layer, worlds/Blue/SimonsAbatis/SimonsAbatis_Layers/OPFOR/OPFORPlayer.layer
*Add T72 for OPFOR
* Fixed Replication Bug caused by change of Material for the BTRs
* Updated Brief
Put a brief summary of the mission added or updated here.
Put any specifics the mission reviewer needs to look out for or double check here.
If this mission is dependent on a pull request to GC units or core, or the TilW framework, link it here.
If this mission is dependent on a mod not currently on the GC mod list, put it here, though understand rejected or incompatible mods may require substantial changes to your mission.
=> V2 Simon Abatis

Missions/FloridaMan/AssaultOnCastleKrona.conf, Missions/FloridaMan/AssaultOnCastleKrona.conf.meta, worlds/FloridaMan/worlds/AssaultOnCastleKrona/AssaultOnCastleKrona.ent, worlds/FloridaMan/worlds/AssaultOnCastleKrona/AssaultOnCastleKrona.ent.meta, worlds/FloridaMan/worlds/AssaultOnCastleKrona/AssaultOnCastleKrona_Layers/Briefing.layer, worlds/FloridaMan/worlds/AssaultOnCastleKrona/AssaultOnCastleKrona_Layers/CDF.layer, worlds/FloridaMan/worlds/AssaultOnCastleKrona/AssaultOnCastleKrona_Layers/RF.layer, worlds/FloridaMan/worlds/AssaultOnCastleKrona/AssaultOnCastleKrona_Layers/default.layer
Russian understrength infantry company assaults Castle Krona, currently held by CDF special forces.
Should be a pretty simple TVT.
None
=> Add TVT(44-80) Assault on Castle Krona

worlds/Blue/DirectionFound/Prefabs/Character_US_80_Driver_P.et, worlds/Blue/DirectionFound/Prefabs/Character_US_80_Gunner_P.et
He used my M16A1 in some units in Direction Found, which I have since removed, have now given them the Chungus M16
=> Fixing Blue's mission (my fault)

Missions/HitTheMan/Battle For Zarichne NVA ATK/BattleForZarichneNVAATK.conf, Missions/HitTheMan/Battle For Zarichne NVA ATK/BattleForZarichneNVAATK.conf.meta, worlds/HitTheMan/Battle For Zarichne NVA ATK/BattleForZarichneNVAATK.ent, worlds/HitTheMan/Battle For Zarichne NVA ATK/BattleForZarichneNVAATK.ent.meta, worlds/HitTheMan/Battle For Zarichne NVA ATK/BattleForZarichneNVAATK_Layers/CORE/All_Brief.layer, worlds/HitTheMan/Battle For Zarichne NVA ATK/BattleForZarichneNVAATK_Layers/CORE/MortarStrikes.layer, worlds/HitTheMan/Battle For Zarichne NVA ATK/BattleForZarichneNVAATK_Layers/CORE/Props.layer, worlds/HitTheMan/Battle For Zarichne NVA ATK/BattleForZarichneNVAATK_Layers/CORE/Pub_Markers.layer, worlds/HitTheMan/Battle For Zarichne NVA ATK/BattleForZarichneNVAATK_Layers/NVA_Players/NVA_Briefings.layer, worlds/HitTheMan/Battle For Zarichne NVA ATK/BattleForZarichneNVAATK_Layers/NVA_Players/NVA_Markers.layer, worlds/HitTheMan/Battle For Zarichne NVA ATK/BattleForZarichneNVAATK_Layers/NVA_Players/NVA_Players.layer, worlds/HitTheMan/Battle For Zarichne NVA ATK/BattleForZarichneNVAATK_Layers/US_Players/US_Brief.layer, worlds/HitTheMan/Battle For Zarichne NVA ATK/BattleForZarichneNVAATK_Layers/US_Players/US_Markers.layer, worlds/HitTheMan/Battle For Zarichne NVA ATK/BattleForZarichneNVAATK_Layers/US_Players/US_Players.layer, worlds/HitTheMan/Battle For Zarichne NVA ATK/BattleForZarichneNVAATK_Layers/default.layer
East German Army is sending a Motor Rifle Platoon (+) with T-72A support to clear out the town of Zarichne, while the US Army Units are tasked with defending the town with a Rifle Platoon (-) and a Bradley section.
None
T-72A NVA Variant
=> TVT (55-71) Battle For Zarichne (NVA Attack) V1.0

worlds/James/BootnecksAndBTRs/BootnecksAndBTRs_Layers/uk_brief.layer, worlds/James/BootnecksAndBTRs/BootnecksAndBTRs_Layers/ussr_brief.layer
Adjustments made to hopefully make task clearer to the PLs.
=> Briefing adjustments to Bootnecks and BTRs

Missions/James/LehtoTussle.conf, Missions/James/LehtoTussle.conf.meta, worlds/James/BootnecksAndBTRs/BootnecksAndBTRs_Layers/ussr.layer, worlds/James/BootnecksAndBTRs/BootnecksAndBTRs_Layers/ussr_brief.layer, worlds/James/LehtoTussle/LehtoTussle.ent, worlds/James/LehtoTussle/LehtoTussle.ent.meta, worlds/James/LehtoTussle/LehtoTussle_Layers/blu_brief.layer, worlds/James/LehtoTussle/LehtoTussle_Layers/blu_markers.layer, worlds/James/LehtoTussle/LehtoTussle_Layers/blu_players.layer, worlds/James/LehtoTussle/LehtoTussle_Layers/default.layer, worlds/James/LehtoTussle/LehtoTussle_Layers/red_brief.layer, worlds/James/LehtoTussle/LehtoTussle_Layers/red_markers.layer, worlds/James/LehtoTussle/LehtoTussle_Layers/red_players.layer, worlds/James/OrbSturm/EffectModule_Zoned_MortarBarrage_Larger.et
New mission: British Royal Marine troop attacks Soviet motor rifles
Updates to old mission - hopefully fixed BTR not moving during setup issue, plus briefing tweak. Adjustment to Orb Sturm mortar barrages
- [ y] Briefing, map, slotting screen
- [ y] Setup timers / AO Limits
- [ n/a] Custom prefabs
- [ y] Key framework events and interactions (QRFs, etc)
- [ y] End conditions
- [ y] Playable in Dedicated Server Tool / Peer Tool
none
n/a
=> New Mission (TVT48-66 Lehto Tussle) + Updates to Bootnecks and BTRs and Orb Sturm

worlds/James/LehtoTussle/LehtoTussle_Layers/blu_brief.layer, worlds/James/LehtoTussle/LehtoTussle_Layers/blu_players.layer, worlds/James/LehtoTussle/LehtoTussle_Layers/default.layer, worlds/James/LehtoTussle/LehtoTussle_Layers/red_brief.layer, worlds/James/LehtoTussle/LehtoTussle_Layers/red_players.layer
Adjust balance, now 2:1.
Minor briefing tweaks
=> Lehto Tussle Update

worlds/Elite/DesertHeat/DesertHeat_Layers/Briefing.layer, worlds/Elite/DesertHeat/DesertHeat_Layers/Fortifications.layer, worlds/Elite/DesertHeat/DesertHeat_Layers/Supplies.layer, worlds/Elite/DesertHeat/DesertHeat_Layers/Vehicles.layer, worlds/Elite/DesertHeat/DesertHeat_Layers/default.layer
Adds demo bricks and assault ladders plus an extra vehicle for opfor.
Blufor gets additional fortifications/battlements to the FOB.
Everything works and is tested. :)
Put a brief summary of the mission added or updated here.
- [ x ] Briefing, map, slotting screen
- [ x ] Setup timers / AO Limits
- [ x ] Custom prefabs
- [ x ] Key framework events and interactions (QRFs, etc)
- [ x ] End conditions
- [ x ] Playable in Dedicated Server Tool / Peer Tool
Put any specifics the mission reviewer needs to look out for or double check here.
If this mission is dependent on a pull request to GC …
=> Desert Heat Updates

Missions/Hot Mic/SupplySecureAtMontignac.conf, worlds/HotMic/SupplySecureAtMontignac/SupplySecureAtMontignac_Layers/Briefing.layer, worlds/HotMic/SupplySecureAtMontignac/SupplySecureAtMontignac_Layers/TeamRed.layer, worlds/HotMic/SupplySecureAtMontignac/SupplySecureAtMontignac_Layers/default.layer
Secure and extract designated “FOOD” supply trucks located within the Montignac.
- Replace Mission Mode
- Update Briefing
N/A
N/A
=> Update Mission: COTVT (20-62) Secure Supplies at Montignac (v1.2)

.gitignore, Missions/FloridaMan/AAS_ValleyStreetFight.conf, Missions/FloridaMan/AAS_ValleyStreetFight.conf.meta, worlds/FloridaMan/worlds/AAS/AAS_ValleyStreetFight/AAS_ValleyStreetFight.ent, worlds/FloridaMan/worlds/AAS/AAS_ValleyStreetFight/AAS_ValleyStreetFight.ent.meta, worlds/FloridaMan/worlds/AAS/AAS_ValleyStreetFight/AAS_ValleyStreetFight_Layers/AAC.layer, worlds/FloridaMan/worlds/AAS/AAS_ValleyStreetFight/AAS_ValleyStreetFight_Layers/PlayerSpawns.layer, worlds/FloridaMan/worlds/AAS/AAS_ValleyStreetFight/AAS_ValleyStreetFight_Layers/Til.layer, worlds/FloridaMan/worlds/AAS/AAS_ValleyStreetFight/AAS_ValleyStreetFight_Layers/Zones.layer, worlds/FloridaMan/worlds/AAS/AAS_ValleyStreetFight/AAS_ValleyStreetFight_Layers/default.layer
New AAS on Kunar. US Army and Insurgent forces battle it out over a town just outside the airport.
Yes.
- ~~Briefing, map, slotting screen~~
- ~~Setup timers / AO Limits~~
Uses AAS framework. Seeder mission.
N/A
=> Added AAS Valley Street Fight on Kunar.

Missions/Cunnah/Local_Problems.conf, worlds/Cunnah/Local_Problems/Local_Problems_Layers/Brief_OPFOR.layer, worlds/Cunnah/Local_Problems/Local_Problems_Layers/INDFOR_AI.layer, worlds/Cunnah/Local_Problems/Local_Problems_Layers/Markers.layer, worlds/Cunnah/Local_Problems/Local_Problems_Layers/OPFOR.layer, worlds/Cunnah/Local_Problems/Local_Problems_Layers/OPFOR_AI.layer, worlds/Cunnah/Local_Problems/Local_Problems_Layers/Props.layer, worlds/Cunnah/Local_Problems/Local_Problems_Layers/default.layer
Local Garrison needs to be rescued from angry militia. Changed BTRs to GAZ-TIGRs so everyone gets a view.
All Tested (minor update).
Minor changes changed vehicles double checked it still works fine.
=> Local Problems V3 (Updated)

worlds/Jub/MissionWithAssets/MissionWithAssets_Layers/briefing_usmc.layer, worlds/Jub/MissionWithAssets/MissionWithAssets_Layers/vehicles.layer
removed a crows II jav
added a JLTV with tow 
updated brief to reflect that
n/a
needs JLTV with tow PR in GC units
=> mission with assets update

Missions/Hot Mic/VehicleInterdictionAtKunarCOOP.conf, worlds/HotMic/VehicleInterdictionCOOPKunar/VehicleInterdictionCOOPKunar_Layers/Briefings.layer, worlds/HotMic/VehicleInterdictionCOOPKunar/VehicleInterdictionCOOPKunar_Layers/GreenTeam.layer, worlds/HotMic/VehicleInterdictionCOOPKunar/VehicleInterdictionCOOPKunar_Layers/Vehicles.layer, worlds/HotMic/VehicleInterdictionCOOPKunar/VehicleInterdictionCOOPKunar_Layers/default.layer
- Reduce Player count from (21-29) to (3-14)
- Update Freeze time and spawn timers for 3 convoys
- Update Briefing descriptions 
N/A
N/A
=> Update Mission: COOP (3-14) Vehicle Interdiction at Kunar

worlds/Corax/SummerDays/SummerDays_Layers/RM.layer, worlds/Corax/SummerDays/SummerDays_Layers/briefing.layer, worlds/Corax/SummerDays/SummerDays_Layers/default.layer
Fix for the mortar script. Illum doesn't currently work with this script.
=> Fixed mortar script and edited briefing to reflect changes.
